export class Car {
  makeId?: number;
  makeName: string;
  modelId?: number;
  modelName: string;
  trimId?: number;
  trimYear: number;
  trimName?: string;
  trimDescription?: string;
  trimMsrp?: number;
  trimInvoice?: number;
  trimCreated?: string;
  trimModified?: string;
  engineId?: number;
  engineType?: string;
  engineFuelType?: string;
  engineCylinders?: string;
  engineSize?: number;
  engineHorsepowerHp?: number;
  engineHorsepowerRpm?: number;
  engineTorqueFtLbs?: number;
  engineTorqueRpm?: number;
  engineValves?: number;
  engineValveTiming?: string;
  engineCamType?: string;
  engineDriveType?: string;
  engineTransmission?: string;
  bodyId?: number;
  bodyType?: string;
  bodyDoors?: number;
  bodySeats?: number;
  bodyLength?: number;
  bodyWidth?: number;
  bodyHeight?: number;
  bodyWheelBase?: number;
  bodyFrontTrack?: number;
  bodyRearTrack?: number;
  bodyGroundClearance?: number;
  bodyCargoCapacity?: number;
  bodyMaxCargoCapacity?: number;
  bodyCurbWeight?: number;
  bodyGrossWeight?: number;
  bodyMaxPayload?: number;
  bodyMaxTowingCapacity?: number;
  mileageId?: number;
  mileageFuelTankCapacity?: number;
  mileageCombinedMpg?: number;
  mileageEpaCityMpg?: number;
  mileageEpaHighwayMpg?: number;
  mileageRangeCity?: number;
  mileageRangeHighway?: number;
  price?: number;

  constructor(data: any) {
    this.makeId = data.makeId;
    this.makeName = data.makeName;
    this.modelId = data.modelId;
    this.modelName = data.modelName;
    this.trimId = data.trimId;
    this.trimYear = data.trimYear;
    this.trimName = data.trimName;
    this.trimDescription = data.trimDescription;
    this.trimMsrp = data.trimMsrp;
    this.trimInvoice = data.trimInvoice;
    this.trimCreated = data.trimCreated;
    this.trimModified = data.trimModified;
    this.engineId = data.engineId;
    this.engineType = data.engineType;
    this.engineFuelType = data.engineFuelType;
    this.engineCylinders = data.engineCylinders;
    this.engineSize = data.engineSize;
    this.engineHorsepowerHp = data.engineHorsepowerHp;
    this.engineHorsepowerRpm = data.engineHorsepowerRpm;
    this.engineTorqueFtLbs = data.engineTorqueFtLbs;
    this.engineTorqueRpm = data.engineTorqueRpm;
    this.engineValves = data.engineValves;
    this.engineValveTiming = data.engineValveTiming;
    this.engineCamType = data.engineCamType;
    this.engineDriveType = data.engineDriveType;
    this.engineTransmission = data.engineTransmission;
    this.bodyId = data.bodyId;
    this.bodyType = data.bodyType;
    this.bodyDoors = data.bodyDoors;
    this.bodySeats = data.bodySeats;
    this.bodyLength = data.bodyLength;
    this.bodyWidth = data.bodyWidth;
    this.bodyHeight = data.bodyHeight;
    this.bodyWheelBase = data.bodyWheelBase;
    this.bodyFrontTrack = data.bodyFrontTrack;
    this.bodyRearTrack = data.bodyRearTrack;
    this.bodyGroundClearance = data.bodyGroundClearance;
    this.bodyCargoCapacity = data.bodyCargoCapacity;
    this.bodyMaxCargoCapacity = data.bodyMaxCargoCapacity;
    this.bodyCurbWeight = data.bodyCurbWeight;
    this.bodyGrossWeight = data.bodyGrossWeight;
    this.bodyMaxPayload = data.bodyMaxPayload;
    this.bodyMaxTowingCapacity = data.bodyMaxTowingCapacity;
    this.mileageId = data.mileageId;
    this.mileageFuelTankCapacity = data.mileageFuelTankCapacity;
    this.mileageCombinedMpg = data.mileageCombinedMpg;
    this.mileageEpaCityMpg = data.mileageEpaCityMpg;
    this.mileageEpaHighwayMpg = data.mileageEpaHighwayMpg;
    this.mileageRangeCity = data.mileageRangeCity;
    this.mileageRangeHighway = data.mileageRangeHighway;
    this.price = data.price;
  }
}
